#ifndef KITTY_METRICS_RENDERINGTYPE_H
#define KITTY_METRICS_RENDERINGTYPE_H

enum RenderingType
{
    SINTEL_ALBEDO = 0,
    SINTEL_CLEAN = 1,
    SINTEL_FINAL = 2
};


#endif //KITTY_METRICS_RENDERINGTYPE_H
